### ISSUE TITLE
Windows 10 not working

### ISSUE THREAD

**Issue by Majinek** [GkevinOD/MSL-Bot-AutoIT#1]
Hello wanted to test bot but it's only asking me for energy cost, energy i have etc. bot just staying idle when script is going and nothing happens :/ Is there a fix for this or i need to VMare on Win 7?

**Comment by GkevinOD** [comment]
Hey, this project was mostly intended for me but it could work for other people with some optimizing. 

To run this script, you must run as x86. To do that, right click the file and select that option. It should work for windows 10, because i have that OS. 

You can test if the bot is successfully capturing image data by running this line in the editor: 

CaptureRegion("test.bmp")

This will generate a file with the captured screen of bluestacks. If it the screen is completely black, then you have to wait for me to update the capture system. Otherwise you are one step closer to being able to run the bot.

If all goes well with screen capture, you can test if the images that is optimized for my computer will work for you. Try this line while you are in the map:

setLog(getLocation())

If it returns unknown, then you may have to replace all of the images in the images folder. If it returns 'map' the. The script might work for you.

**Comment by GkevinOD** [comment]
Correction: its is suppose to be _CaptureRegion("test.bmp")

**Comment by dcloud102** [comment]
Thank you.

**Comment by Majinek** [comment]
Thank You for the reply really nice work with bot :)

**Comment by GkevinOD** [comment]
Sure thing, tell me your results. I'll be on for the next few hours, so I can help you guys out.

**Comment by dcloud102** [comment]
If I want to change it to Nox app player, do I just change the information
on the Global Variable file?

**Comment by GkevinOD** [comment]
Nox will not work due to the capture system I'm using. It is suppose to be background capture which Nox somehow blocks.

**Comment by Majinek** [comment]
what about MEmu? coz i have problems with bluestacks or which version is the best of bs?

**Comment by dcloud102** [comment]
I can't seem to get my bluestack to be 800x600.

**Comment by GkevinOD** [comment]
The bluestacks I use is actually: bluestacks rooted 0.10.7.5601. You can search that in google to download it.

**Comment by GkevinOD** [comment]
For the resolution, you have to go to the regedit or registry editor and change the both GuestWidth/Height and WindowWidth/Height which is my setting.

**Comment by GkevinOD** [comment]
To navigate the registry: HKEY_LOCAL_MACHINE -> SOFTWARE -> BlueStacks -> Guest -> Android -> FrameBuffer -> 0

**Comment by dcloud102** [comment]
Ah... I'll give it a try.  Thank you for your help and in sharing value knowledge and codes.

**Comment by dcloud102** [comment]
Are you running bluestack in window mode or full screen mode?

**Comment by GkevinOD** [comment]
Window mode. Test the capture region thing that I posted earlier and see if that works.

**Comment by dcloud102** [comment]
It capture my computer screen from top left to bottom right at 800x600.  I would have to keep my blue stack window at that location.  Is this how you are doing it?

**Comment by GkevinOD** [comment]
It's did not capture just bluestacks? It should just be bluestacks

**Comment by GkevinOD** [comment]
If not, pull up the autoit window info that comes with autoit and use the finder tool (the one with the crosshair) and drag it on the bluestacks window. It should give you a Title, tell me what that Title is

**Comment by dcloud102** [comment]
![image](https://cloud.githubusercontent.com/assets/24919677/22760830/d224daee-ee1d-11e6-893a-ba75107c0d3d.png)

**Comment by dcloud102** [comment]
![test](https://cloud.githubusercontent.com/assets/24919677/22760875/0c3b580c-ee1e-11e6-8475-16baa260b7a4.jpg)

**Comment by dcloud102** [comment]
For some reason, my blue stack window is not displaying correctly as well.  I change the Guest Width/Height and Windows Width/Height per your instructions, and my blue stack is not displaying correctly.

**Comment by GkevinOD** [comment]
You have to restart bluestacks for that. Also I notice you are running window 7, so I think you may need to disable your aero effect. You can do a quick google search on that

**Comment by GkevinOD** [comment]
To restart, you can right click the icon on the bottom right notification thing

**Comment by GkevinOD** [comment]
Also check on the autoit window info the control tab and see if the advanced mode matches the one on the global variables file

**Comment by Majinek** [comment]
Ok now i am on pc so will begin testing hope it will work :)

**Comment by dcloud102** [comment]
![image](https://cloud.githubusercontent.com/assets/24919677/22761219/70fe9a0a-ee1f-11e6-9020-30e1a6e9db15.png)

**Comment by GkevinOD** [comment]
Actually, the aero effect should be turned on. I forgot.

**Comment by dcloud102** [comment]
My screen resolution is messed up and I verified that the Global Variables are correct.

**Comment by GkevinOD** [comment]
Oh I forgot, you must run bluestacks before running the bot. Try again restart the autoit file

**Comment by dcloud102** [comment]
Got my capture to be corrected. I just copy and pasted the Autoit info from the control tab and pasted it into your Global Variable and it worked.

**Comment by GkevinOD** [comment]
Okay so it is aligned now right?

**Comment by dcloud102** [comment]
I got the bot to captured correctly.  But my bluestack window is not correct.

**Comment by GkevinOD** [comment]
Did you restart bluestacks?

**Comment by dcloud102** [comment]
I closed bluestacks multiple times.

**Comment by GkevinOD** [comment]
Try going into the notification icons on the bottom right of your screen (where the internet connection icon is). Right click on blue stacks and click restart

**Comment by dcloud102** [comment]
The problem is that I cannot see the that area in my blue stack app.

**Comment by GkevinOD** [comment]
So the resolution is the one previous inside bluestacks, but the window is different size?

**Comment by Majinek** [comment]
there is good program to change resolution for bs it's called ScreeRee_v08

**Comment by GkevinOD** [comment]
Usually restarting bluestacks fixes that problem. Try to close all instances of bluestacks in task manager and running bluestacks again

**Comment by dcloud102** [comment]
Wow.  Thanks.  I was looking for bluestack in my task manager but it was under some other names like HD-Agent.exe and not Bluestack.  Restart and it is working now.

**Comment by GkevinOD** [comment]
Okay now, go to msl and try setLog(getLocation()) in the map and tell me what it outputs

**Comment by dcloud102** [comment]
This might take awhile as I need to download the app in bluestack.

**Comment by Majinek** [comment]
Bot is working good but one question it stucks on tasks like phantom-forest normal it wont choose to go further same is on golem grind i write all info and B4 for farm and it stucks on difficulty choose. Do I need to change img?

**Comment by GkevinOD** [comment]
Currently, I haven't implemented any algorithms that take you to b1-b6 of golems. I'll do that in the next update, maybe by tomorrow or today.

**Comment by GkevinOD** [comment]
And also, some images might not work because on my game setting, it is on low-res mode

**Comment by Majinek** [comment]
ah ok :( Second question is rare farming it stucks on choosing path i am also on low-res mode

**Comment by GkevinOD** [comment]
Choosing path? Is it where you select which stage you want to go into?

**Comment by Majinek** [comment]
yup it goes to ex phantom forest and stucks on stage select

**Comment by GkevinOD** [comment]
Okay so there is a image called stage-energy <- you might need to replace that one

**Comment by GkevinOD** [comment]
When I make an update, I'll have an algorithm that takes the images based on your screen, because all of the images are optimized for me

**Comment by GkevinOD** [comment]
Hold on, what was your input when it asked you for image name and the stage thing?

**Comment by GkevinOD** [comment]
When you enter the stage level: 0 is normal, 1 is hard, 2 is expert

**Comment by Majinek** [comment]
oooh that's why it wasn't working now i get it

**Comment by Majinek** [comment]
Nope still looping with choosing phantom forest and closing it

**Comment by GkevinOD** [comment]
Can you tell me exactly what its doing? The steps

**Comment by Majinek** [comment]
ok tested it on aria-lake 1 < it choose normal difficulty working if battle ends will test it with rest. :)

**Comment by Majinek** [comment]
when i wrote 0 it was just looping with opening phantom-forest map and closing it and reopening again

**Comment by Majinek** [comment]
With which emulators bot is compatibille? This version of bs which i have, has a lot of graphical bugs maybe this is affecting bot too?

**Comment by GkevinOD** [comment]
I have graphical bugs on mine too, like the animations are sometimes black. But it shouldn't have an issue 
because all of the images should be static

**Comment by Majinek** [comment]
![image](https://cloud.githubusercontent.com/assets/25628438/22762572/5d57a078-ee60-11e6-96e1-fd508139b232.png)
I think now it's working like charm. Will test it more and more :) Really great job :) Do You have patreon or smth like that? Willing to donate for beers < to keep up good work :)

**Comment by GkevinOD** [comment]
I don't, I just do this for code for fun. I'll be implementing other stuff later on

**Comment by Majinek** [comment]
Tried coding in past, don't know why but never had good motivation and someone to teach me. Now i am mad at me that I wasn't doing it for learning purposes nor for fun only it was like oh i will be programmer and next day meh this is not for me and for this day have regrets.
