### ISSUE TITLE
Need A Little Assistance, If Possible

### ISSUE THREAD

**Issue by oor0m3sdsoo** [GkevinOD/MSL-Bot-AutoIT#4]
First off, the bot looks great. Once I can get this working, I would love to know how I can donate to you. Here's my dilemma:

-- Downloaded the rooted Blue Stacks that you had posted.
-- Ran Autoit (Not sure if I'm running as 32-bit). I ran Autoit and not the Autoitx64 file, so I would assume.
-- There are black boxes around some of the images (Blue Stacks is in 800x600) on the airship
-- I selected the script to run and started the script, but I just see Zeros in the stats.

Any help that you can provide would be great! Thank you in advance.

Note: When I right-click on the file, there is not option for a 32-bit. I just open, and nothing happens. Any thoughts?

**Comment by GkevinOD** [comment]
Hello, this repository will be discontinued and a new repository with new bot will be here:

https://github.com/GkevinOD/miho-bot

I am creating a more user friendly gui (window) and also an adjustment system for different computers to be able to run scripts. No working version as of now, but in a few days a simple working version that farms rares, exotics and the sorts will be available in the new repository.
